---
name: Rebuild Generated Files

# yamllint disable-line rule:truthy
on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - main

permissions:
  contents: write

jobs:
  rebuild-generated-files:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Rebuild the generated files
        run: make clean build

      - name: Check for changed files
        id: check-changes
        run: |
          if git diff --exit-code > /dev/null; then
            echo "changes=false" >> "${GITHUB_OUTPUT}"
          else
            echo "changes=true" >> "${GITHUB_OUTPUT}"
          fi

      - name: Commit and push changes
        if: (steps.check-changes.outputs.changes == 'true')
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Regenerate files"
          git push origin "HEAD:${BRANCH}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
